// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Codex CLI adapter - pure TOML config artifact generator (Slice 1).

import { buildAuthoritativeAllowlist } from "./allowlist.js";
import {
  CODEX_REQUIRED_AUTHORITATIVE_TOOLS,
  type CodexConfigOverride,
  type CodexMcpBridgePlan,
  type CodexMcpBridgePlanInput,
  type CodexMcpConfigArtifact,
  type CodexMcpConfigInput,
  DREAMGRAPH_AUTHORITATIVE_SERVER_NAME,
} from "./types.js";

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlArray(values: readonly string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

function tomlInlineTable(values: Readonly<Record<string, string>>): string {
  const entries = Object.keys(values)
    .sort()
    .map((key) => `${key} = ${tomlString(values[key] ?? "")}`);
  return `{ ${entries.join(", ")} }`;
}

const COMPUTER_FEATURES = ["computer_use", "browser_use", "browser_use_external", "browser_use_full_cdp_access", "in_app_browser"] as const;
function computerFeatureLines(granted: boolean): string[] {
  return COMPUTER_FEATURES.map(feature => `${feature} = ${granted && feature !== "browser_use_full_cdp_access" ? "true" : "false"}`);
}

export function buildCodexMcpConfig(
  input: CodexMcpConfigInput,
): CodexMcpConfigArtifact {
  validateCodexMcpConfigInput(input);

  const env = codexMcpEnv(input);
  const content = [
    "# Generated by DreamGraph for an isolated Codex CLI run.",
    "# Do not copy this file into the user's persistent CODEX_HOME.",
    // Codex native Computer Use only when the instance policy grants it for this run.
    "[computer_use]",
    `default_app_access = ${tomlString(input.computerUse === true ? "allow" : "deny")}`,
    "",
    "[features]",
    ...computerFeatureLines(input.computerUse === true),
    "",
    `[mcp_servers.${DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}]`,
    `command = ${tomlString(input.dreamgraphCommand)}`,
    `args = ${tomlArray(input.dreamgraphArgs)}`,
    `env = ${tomlInlineTable(env)}`,
    `default_tools_approval_mode = ${tomlString("auto")}`,
    "",
  ].join("\n");

  return {
    filename: "config.toml",
    content,
    metadata: {
      runId: input.runId,
      authoritativeServer: DREAMGRAPH_AUTHORITATIVE_SERVER_NAME,
      allowlist: Object.freeze([...input.allowlist]),
    },
  };
}

export function buildCodexMcpConfigOverrides(
  input: CodexMcpConfigInput,
): readonly CodexConfigOverride[] {
  validateCodexMcpConfigInput(input);
  const env = codexMcpEnv(input);
  return Object.freeze([
    // Overrides also apply when a companion host uses its existing CLI home.
    // Native computer access follows the instance policy grant; otherwise it stays disabled.
    { key: "computer_use.default_app_access", value: tomlString(input.computerUse === true ? "allow" : "deny") },
    ...COMPUTER_FEATURES.map(feature => ({ key: `features.${feature}`, value: String(input.computerUse === true && feature !== "browser_use_full_cdp_access") })),
    { key: `mcp_servers.${DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}.command`, value: tomlString(input.dreamgraphCommand) },
    { key: `mcp_servers.${DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}.args`, value: tomlArray(input.dreamgraphArgs) },
    { key: `mcp_servers.${DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}.env`, value: tomlInlineTable(env) },
    { key: `mcp_servers.${DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}.default_tools_approval_mode`, value: tomlString("auto") },
  ]);
}

function validateCodexMcpConfigInput(input: CodexMcpConfigInput): void {
  if (!input.runId) {
    throw new Error("buildCodexMcpConfig: runId is required");
  }
  if (!input.transportToken) {
    throw new Error("buildCodexMcpConfig: transportToken is required");
  }
  if (!input.dreamgraphCommand) {
    throw new Error("buildCodexMcpConfig: dreamgraphCommand is required");
  }
  if (input.allowlist.length === 0) {
    throw new Error("buildCodexMcpConfig: allowlist must contain at least one tool");
  }
}

function codexMcpEnv(input: CodexMcpConfigInput): Readonly<Record<string, string>> {
  return {
    ...(input.dreamgraphEnv ?? {}),
    DREAMGRAPH_MCP_TOKEN: input.transportToken,
    DREAMGRAPH_RUN_ID: input.runId,
  };
}

export function buildCodexMcpBridgePlan(
  input: CodexMcpBridgePlanInput,
): CodexMcpBridgePlan {
  const allowlist = buildAuthoritativeAllowlist(input.liveToolNames);
  if (!allowlist.ok) {
    throw new Error(
      `buildCodexMcpBridgePlan: DreamGraph tool registry mismatch; missing required tools: ${allowlist.missingRequired.join(", ")}`,
    );
  }

  const configInput: CodexMcpConfigInput = {
    runId: input.runId,
    transportToken: input.transportToken,
    dreamgraphCommand: input.dreamgraphCommand,
    dreamgraphArgs: input.dreamgraphArgs,
    dreamgraphEnv: input.dreamgraphEnv,
    allowlist: allowlist.tools,
    ...(input.computerUse === true ? { computerUse: true } : {}),
  };
  const config = buildCodexMcpConfig(configInput);

  return {
    allowlist,
    config,
    configOverrides: buildCodexMcpConfigOverrides(configInput),
    registry: {
      authoritativeServer: DREAMGRAPH_AUTHORITATIVE_SERVER_NAME,
      requiredTools: CODEX_REQUIRED_AUTHORITATIVE_TOOLS,
      allowedTools: allowlist.tools,
      missingRequired: allowlist.missingRequired,
    },
  };
}

export function serializeCodexMcpConfig(
  artifact: CodexMcpConfigArtifact,
): string {
  return artifact.content;
}
